/* 

JAVASCRIPT TASKS COMPLETION - (17/22)

------------------------------------------

NUMBER EXERCISES (4) (4/4 = ALL DONE)

STRING EXERCISES (6) (6/6 = ALL DONE) 

STRINGS II EXERCISE (1) (0/1) (INCOMPLETE)

CONTROL FLOW EXERCISES (2) (2/2 DONE?)

IF STATEMENT DICE GAME (1) (1/1 ALL DONE)

FUNCTIONS EXERCISE (8) (4/8) (INCOMPLETE) (Unfinished 5-8)

*/